name: Deploy CRM Templates Handler

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - qa

run-name: "@${{ github.actor }} deploy crm-templates-handler to ${{ inputs.environment }}"

env:
  CI_DIR: crm-templates-handler

jobs:
  cicd-setup:
    uses: BetssonGroup/cicd-setup/.github/workflows/setup.yml@v4.2
    with:
      size: "medium"
      count: 1
      base-image: "container-registry.test.betsson.tech/betsson/cloudops/github-agent-basic:latest"

  deploy:
    name: Deploy CRM Templates Handler
    needs: cicd-setup
    runs-on: ${{ fromJSON(needs.cicd-setup.outputs.runs-on) }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ secrets.OBG_GHACTION_TOKEN }}
          path: ${{ env.CI_DIR }}

      - name: Deploy to test
        if: inputs.environment == 'test'
        uses: BetssonGroup/bego-action@d5267021db21f94333a3abe7bd78e4dd2882068c # v8.0.1
        with:
          username: ${{ secrets.BEGO_USER }}
          password: ${{ secrets.BEGO_PASSWORD }}
          test-rancher-token: ${{ secrets.BEGO_TIERS_TEST_RANCHERTOKEN }}
          prod-rancher-token: ${{ secrets.BEGO_TIERS_PROD_RANCHERTOKEN }}
          version: ${{ vars.BEGO_VERSION }}
          app-id: ${{ vars.BEGO_RELEASE_DOWNLOADER_APPID }}
          private-key: ${{ secrets.BEGO_RELEASE_DOWNLOADER_PRIVATEKEY }}
          workdir: ${{ env.CI_DIR }}
          command: >
            bego version &&
            bego deploy test --ignore-already-deployed --wait 15m
            --ignore-git-check --op-in-prog-mitigation --verbose -l debug

      - name: Deploy to qa
        if: inputs.environment == 'qa'
        uses: BetssonGroup/bego-action@d5267021db21f94333a3abe7bd78e4dd2882068c # v8.0.1
        with:
          username: ${{ secrets.BEGO_USER }}
          password: ${{ secrets.BEGO_PASSWORD }}
          test-rancher-token: ${{ secrets.BEGO_TIERS_TEST_RANCHERTOKEN }}
          prod-rancher-token: ${{ secrets.BEGO_TIERS_PROD_RANCHERTOKEN }}
          version: ${{ vars.BEGO_VERSION }}
          app-id: ${{ vars.BEGO_RELEASE_DOWNLOADER_APPID }}
          private-key: ${{ secrets.BEGO_RELEASE_DOWNLOADER_PRIVATEKEY }}
          workdir: ${{ env.CI_DIR }}
          command: >
            bego version &&
            bego deploy qa --ignore-already-deployed --wait 15m
            --ignore-git-check --op-in-prog-mitigation --verbose -l debug
